"""
Pydantic Data Models for FocusFlow — non-task schemas.

Task models have moved to app.tasks.models (self-contained package).
They are re-exported here so any existing import paths continue to work.
"""

from datetime import datetime
from typing import Optional, List
from pydantic import BaseModel, EmailStr, Field
from enum import Enum

# ── Task model re-exports (backward-compat) ───────────────────────────────────
# These now live in app.tasks.models — import from there for new code.
from app.tasks.models import (          # noqa: F401
    Priority,
    TaskStatus,
    SubtaskCreate,
    SubtaskResponse,
    TaskCreate,
    TaskUpdate,
    TaskResponse,
)


# ── Timer Enum ────────────────────────────────────────────────────────────────

class TimerPhase(str, Enum):
    FOCUS = "FOCUS"
    SHORT_BREAK = "SHORT_BREAK"
    LONG_BREAK = "LONG_BREAK"


# ── Auth Models ───────────────────────────────────────────────────────────────

class UserRegister(BaseModel):
    """Request model for user registration."""
    name: str = Field(..., min_length=2, max_length=100)
    email: EmailStr
    password: str = Field(..., min_length=8)


class UserLogin(BaseModel):
    """Request model for user login."""
    email: EmailStr
    password: str


class UserResponse(BaseModel):
    """Response model returned after auth — never includes password hash."""
    id: str
    name: str
    email: str


class TokenResponse(BaseModel):
    """JWT token response returned on successful login or registration."""
    access_token: str
    token_type: str = "bearer"
    user: UserResponse


# ── Timer Models ──────────────────────────────────────────────────────────────

class PomodoroSessionCreate(BaseModel):
    """Request model for logging a completed Pomodoro work session."""
    task_id: Optional[str] = None
    phase: TimerPhase = TimerPhase.FOCUS
    duration_minutes: int = Field(25, ge=1, le=60)


class PomodoroSessionResponse(PomodoroSessionCreate):
    """Response model for a logged Pomodoro session."""
    id: str
    user_id: str
    completed_at: datetime


# ── Calendar Models ───────────────────────────────────────────────────────────

class TimeBlockCreate(BaseModel):
    """
    Request model for creating a calendar time block.

    Args:
        title:                Label shown on the calendar block.
        start_time:           ISO datetime string for block start.
        end_time:             ISO datetime string for block end.
        task_id:              Optional linked task ID.
        color:                Optional hex color string persisted per block.
        recurrence:           Recurrence pattern (NONE | DAILY | WEEKDAYS | WEEKLY | MONTHLY).
                              Stored for display and edit-scope awareness; the block series is
                              identified by recurrence_group_id.
        recurrence_group_id:  UUID-like string shared by all blocks in a recurring series.
                              Null for one-off blocks.
    """
    title: str = Field(..., min_length=1)
    start_time: str
    end_time: str
    task_id: Optional[str] = None
    color: Optional[str] = None
    recurrence: str = "NONE"
    recurrence_group_id: Optional[str] = None


class TimeBlockResponse(TimeBlockCreate):
    """Response model for a calendar time block."""
    id: str
    user_id: str


class BulkBlockCreate(BaseModel):
    """Request model for creating multiple time blocks in one call (recurring series)."""
    blocks: List[TimeBlockCreate]



# ── AI Models ─────────────────────────────────────────────────────────────────

class AIBreakdownRequest(BaseModel):
    """Request model for AI task breakdown endpoint."""
    task_id: str
    task_title: str
    task_description: Optional[str] = None


class AIBreakdownResponse(BaseModel):
    """Response model containing AI-generated subtasks."""
    task_id: str
    subtasks: List[str]


class AIPrioritizeRequest(BaseModel):
    """Request model for AI task prioritization endpoint."""
    tasks: List[dict]


class AIPrioritizeResponse(BaseModel):
    """Response model with tasks sorted by AI-assigned priority score."""
    prioritized_tasks: List[dict]


# ── Gemini AI Task Generation Models ─────────────────────────────────────

class AIGenerateTasksRequest(BaseModel):
    """Request model for AI-powered task generation from a goal description."""
    goal: str = Field(..., min_length=1, max_length=1000)


class GeneratedTask(BaseModel):
    """A single task generated by the AI."""
    title: str
    description: str
    priority: Priority = Priority.MEDIUM
    category: str = ""


class AIGenerateTasksResponse(BaseModel):
    """Response containing AI-generated task breakdown."""
    tasks: List[GeneratedTask]
    summary: str


class AIRefineTasksRequest(BaseModel):
    """Request to refine previously generated tasks with user feedback."""
    goal: str
    tasks: List[GeneratedTask]
    feedback: str = Field(..., min_length=1, max_length=1000)


class AISuggestCategoriesRequest(BaseModel):
    """Request to suggest categories for a task title."""
    title: str = Field(..., min_length=1, max_length=500)


class AISuggestCategoriesResponse(BaseModel):
    """Response with suggested category labels."""
    categories: List[str]
